[package]
name = "proj_web"
version = "0.1.0"
edition = "2021"

[dependencies]
proj_lua = { path = "../proj_lua" }

serde = { workspace = true }
serde_json = { workspace = true }
mlua = { workspace = true }
http = { workspace = true }
bytes = "1.10"
http-body = "1.0"
tower-service = "0.3.3"
